version: '2'
services:
  db:
    image: 'bitnami/redis:4.0'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379'
    volumes:
      - ./data:/bitnami
  bigdisk:
    build: .
    restart: always
    links:
      - db
    environment:
      - BIGDISKSUPERADMINEMAIL=
      - BIGDISKURL=
      - BIGDISKEMAILUSERNAME=
      - BIGDISKEMAILPASSWORD=
      - BIGDISKSUPERADMINPASSWORD=
      - REDISLOCATION=redis://db:6379
    volumes:
      - ./files:/files
    ports:
     - '8080:8080'
